### ISSUE TITLE
problem with git submodules

### ISSUE THREAD

**Issue by BacLuc** [addiks/gedit-phpide#2]
When running your plugin in a git submodule, there is a .git file, but no git path.
This is not checked and the storage Layer tries to create an index in
newGryfiPage/concrete5/packages/bacluc_event_package/.git/addiks.phpindex.sqlite3
, but should check that newGryfiPage/concrete5/packages/bacluc_event_package/.git is a file and the git folder is in newGryfiPage/.git

tried to fix it, but the nice function get_git_directory is never called before creating the index.

**Comment by addiks** [comment]
I have just pushed a new version that should have fixed this. Can you please check if this problem is now fixed?

**Comment by BacLuc** [comment]
working now, thank you
