### ISSUE TITLE
autocompletion issue

### ISSUE THREAD

**Issue by BacLuc** [addiks/gedit-phpide#3]
i successfully build the index, but when i try autocompletion, i get the exception
Traceback (most recent call last):
  File "/home/lucius/.local/share/gedit/plugins/gedit-phpide-master/AutocompleteProvider.py", line 196, in do_populate
    hasIter, textIter = context.get_iter()
TypeError: 'TextIter' object is not iterable

**Comment by addiks** [comment]
I have just pushed a new version that should have fixed this. Can you please check if this problem is now fixed?

**Comment by BacLuc** [comment]
is working perfectly, thank you.
